### ISSUE TITLE
Ignored submission file

### ISSUE THREAD

**Issue by DerYeger** [MEws22/lab3Template#1]
Hello,

While committing our solution, I overlooked that the template ignores the output file.
This costed us a point, which is my error in the end (the assignment mentions the file after all).

Still, I recommend not ignoring such files for future templates/assignments, in particular if the offending `.gitignore` isn't in the root directory of the template, but nested as in this case.

https://github.com/MEws22/lab3Template/blob/1f3fc99eae7a951fd8ed327057000a756a002fb0/cpsml.atl/output/.gitignore#L1

Best regards,
Jan Müller

**Comment by MoritzRenkin** [comment]
Agreed. The nested .gitignore is really unexpected in this folder, especially since eclipse does not display .gitignore files in its Project Explorer.
